CREATE DATABASE manufacturing;
USE manufacturing;

CREATE TABLE product (
  ID              BINARY(16)     NOT NULL,
  NAME            VARCHAR(255)   NOT NULL,
  PRICE           DECIMAL(13, 2) NOT NULL,
  MANUFACTURER_ID BINARY(16)     NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE manufacturer (
  ID   BINARY(16)   NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user (
  ID         BINARY(16)   NOT NULL,
  EMAIL      VARCHAR(255) NOT NULL,
  PASSWORD   VARCHAR(255) NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME  VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY EMAIL (EMAIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE role (
  ID   INT(11)      NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY NAME (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE user_role (
  USER_ID BINARY(16) NOT NULL,
  ROLE_ID INT(11)    NOT NULL,
  UNIQUE KEY USER_ID (USER_ID,ROLE_ID),
  CONSTRAINT user_role_ibfk_1 FOREIGN KEY (USER_ID) REFERENCES user (ID),
  CONSTRAINT user_role_ibfk_2 FOREIGN KEY (ROLE_ID) REFERENCES role (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;