USE manufacturing;

CREATE TABLE product (
  ID              BINARY(16)     NOT NULL,
  NAME            VARCHAR(255)   NOT NULL,
  PRICE           DECIMAL(13, 2) NOT NULL,
  MANUFACTURER_ID BINARY(16)     NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE manufacturer (
  ID   BINARY(16)   NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE user (
  ID       INT          NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  UNIQUE (USERNAME),
  PRIMARY KEY (ID)
);

CREATE TABLE role (
  ID   INT          NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  UNIQUE (NAME),
  PRIMARY KEY (ID)
);

CREATE TABLE user_role (
  USER_ID INT NOT NULL,
  ROLE_ID INT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES user (id),
  FOREIGN KEY (ROLE_ID) REFERENCES role (id),
  UNIQUE (USER_ID, ROLE_ID)
);



